### ISSUE TITLE
About planning eval on waymo

### ISSUE THREAD

**Issue by hctian713** [OpenDriveLab/ELM#10]
Hi, it's a nice work!
I notice that you test the planning on waymo dataset. It's structure is differrent from nuscenes, so can you provide the scripts to get waymo trajectory gt and eval ? thanks so much

**Comment by DevLinyan** [comment]
Thank you for your interest. At this time, we don't have plans to release this specific component, as it closely resembles nuScenes. Instead, we're focusing on releasing the data generation aspect for planning in nuScenes soon.

**Comment by hctian713** [comment]
thanks for reply !  Meanwhile, I get another question that the dataset of drivelm is not time-continuous because it's the subset of nuscenes, how you deal with it when training the video module?

**Comment by DevLinyan** [comment]
Good question! Here if we employ the keyframe from the DriveLM for the current QA task, we will utilize the previously consecutive frames from the nuScenes dataset to train the video module.

**Comment by hctian713** [comment]
Are previously frames the keyframe from "samples" file or the frames from "sweeps" file?

**Comment by DevLinyan** [comment]
Here, we solely utilize keyframes from the "samples" files, akin to previous approaches like UniAD and BEVFormer.

**Comment by hctian713** [comment]
get it!&nbsp; thanks so much!&nbsp;
wish you all the best.



---Original---
From: "Linyan ***@***.***&gt;
Date: Thu, Apr 18, 2024 15:39 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [OpenDriveLab/ELM] About planning eval on waymo (Issue #10)




 
Here, we solely utilize keyframes from the "samples" files, akin to previous approaches like UniAD and BEVFormer.
