### ISSUE TITLE
 How to get the evaluate about surrounding narration, Action & Decision?

### ISSUE THREAD

**Issue by LuPaoPao** [OpenDriveLab/ELM#11]
Thank you for your outstanding contributions. How to activate the result of 'B, C, R' of  surrounding narration, Action & Decision in the paper?  Looking forward to your reply.

**Comment by DevLinyan** [comment]
Thank you for your interest. However, I'm a bit confused about the term 'activate'. Could you provide more details about its meaning? If it refers to the process of evaluation, we typically utilize the [language evaluation](https://github.com/bckim92/language-evaluation) approach.

**Comment by LuPaoPao** [comment]
> Thank you for your interest. However, I'm a bit confused about the term 'activate'. Could you provide more details about its meaning? If it refers to the process of evaluation, we typically utilize the [language evaluation](https://github.com/bckim92/language-evaluation) approach.

Thank you very much for your reply. I apologize for my confused consultation. I built my own training evaluation process. I already know the language evaluation approach. However, the QA information for Traffic Sign Inquiry, Surrounding Narration, and Action & Decision I couldn't find.  I only find box det， prediction Prediction and etc. In simple terms, how to get the following form of assessment: 
![1713422950344](https://github.com/OpenDriveLab/ELM/assets/36125195/7f951ed6-1083-41d5-886a-97547a446ce5)

**Comment by DevLinyan** [comment]
The Traffic Sign Inquiry is available in [elm_datasets.py](https://github.com/OpenDriveLab/ELM/blob/7ae27a2b68509a637141a586796bbd63f8c26fcb/lavis/datasets/datasets/elm_datasets.py#L88), and it is generated during the training process.

For the Surrounding Narration and Action & Decision, you can locate them in the DriveLM dataset. In [elm_datasets.py](https://github.com/OpenDriveLab/ELM/blob/7ae27a2b68509a637141a586796bbd63f8c26fcb/lavis/datasets/datasets/elm_datasets.py#L239), `Perception` corresponds to Surrounding Narration, while `Prediction and Planning` corresponds to Action & Decision.

**Comment by LuPaoPao** [comment]
> The Traffic Sign Inquiry is available in [elm_datasets.py](https://github.com/OpenDriveLab/ELM/blob/7ae27a2b68509a637141a586796bbd63f8c26fcb/lavis/datasets/datasets/elm_datasets.py#L88), and it is generated during the training process.
> 
> For the Surrounding Narration and Action & Decision, you can locate them in the DriveLM dataset. In [elm_datasets.py](https://github.com/OpenDriveLab/ELM/blob/7ae27a2b68509a637141a586796bbd63f8c26fcb/lavis/datasets/datasets/elm_datasets.py#L239), `Perception` corresponds to Surrounding Narration, while `Prediction and Planning` corresponds to Action & Decision.

Thank you for your nice reply. It was very helpful and accelerated my process. Thank you again for your outstanding contribution!
