### ISSUE TITLE
Question about preprocess of nuscenes dataset

### ISSUE THREAD

**Issue by fang196** [OpenDriveLab/ELM#12]
In `lavis/datasets/datasets/elm_datasets.py` and `lavis/projects/blip2/train/advqa_t5_elm.yaml`, I found some necessary files that hasn't been mentioned in README.

- How to get `bevdetv2-nuscenes_infos_trainval.pkl`?
- I've seen `drivelm_train.json` in [this link](https://drive.google.com/drive/folders/1QFBIrKqxjn9lfv31XMC3wVIdaAbpMwDL?usp=sharing) , but how can I get 'data/drivelm/val.json' in `advqa_t5_elm.yaml`? Will this file be available in the future?

**Comment by DevLinyan** [comment]
Hi @fang196, the files `bevdetv2-nuscenes_infos_trainval.pkl` have been uploaded to this [link](https://drive.google.com/drive/folders/1QFBIrKqxjn9lfv31XMC3wVIdaAbpMwDL).

DriveLM is conducting the competition using the file `data/drivelm/val.json`. We will release it after the competition concludes.
