### ISSUE TITLE
Question about the usage of box data

### ISSUE THREAD

**Issue by fang196** [OpenDriveLab/ELM#14]
How can I get 'data/embodied/BOXQA_train_v3.json' in [this line](https://github.com/OpenDriveLab/ELM/blob/7ae27a2b68509a637141a586796bbd63f8c26fcb/lavis/datasets/datasets/elm_datasets.py#L320) ?

What is `self.temporal_length` mean in `lavis/datasets/datasets/elm_datasets.py` ?

How can I get `self.traffic_element_dict` in [this line](https://github.com/OpenDriveLab/ELM/blob/7ae27a2b68509a637141a586796bbd63f8c26fcb/lavis/datasets/datasets/elm_datasets.py#L133)?

When will you release file used in this [function](https://github.com/OpenDriveLab/ELM/blob/7ae27a2b68509a637141a586796bbd63f8c26fcb/lavis/datasets/datasets/elm_datasets.py#L88)?

**Comment by DevLinyan** [comment]
Hi, thanks for your interest.
1. `BOXQA_train_v3.json` is essentially the same as `box_detection_train.json`, accessible through this [link](https://drive.google.com/drive/folders/1QFBIrKqxjn9lfv31XMC3wVIdaAbpMwDL).
2. In the Traffic Sign Inquiry, it denotes the time needed for recognition. For instance, we aim to recognize the traffic sign within a span of 3.5 seconds. In Box Detection, it signifies the duration for temporal fusion. For instance, we use frames from the past 1 second for the box detection task.
3. `self. traffic_element_dict` is acquired in this [function](https://github.com/OpenDriveLab/ELM/blob/7ae27a2b68509a637141a586796bbd63f8c26fcb/lavis/datasets/datasets/elm_datasets.py#L88C9-L88C26).
4. We have uploaded it, accessible through this [link](https://drive.google.com/drive/folders/1QFBIrKqxjn9lfv31XMC3wVIdaAbpMwDL).
