### ISSUE TITLE
How to get data/nuscenes/bevdetv2-nuscenes_infos_val.pkl

### ISSUE THREAD

**Issue by CerrieJ** [OpenDriveLab/ELM#16]
I got an error:
FileNotFoundError: [Errno 2] No such file or directory: 'data/nuscenes/bevdetv2-nuscenes_infos_train.pkl'

479     def default_drivelm(self, ann_paths):
480         self.annotation = json.load(open(ann_paths[0], "r"))
481         self.data_info = pickle.load(open("data/nuscenes/bevdetv2-nuscenes_infos_val.pkl", "rb"))["infos"]

How to get data/nuscenes/bevdetv2-nuscenes_infos_val.pkl ? must the nuscenes-Full-dataset (v1.0) ?  It's to big, can I use nuscenes-mini instead?

**Comment by zhouyunsong** [comment]
Yeah I think you definitely can use nuScene-mini but I'm afried you need to generate the pickle file based on the [bevdetv2 repo](bevdetv2-nuscenes_infos_val) (just use the data processing script of nuscenes-devkit)
