### ISSUE TITLE
Question about planning_train/val.json

### ISSUE THREAD

**Issue by hctian713** [OpenDriveLab/ELM#2]
hi, nice work!
I wanna know how you produce the planning_train/val.json?  Is it the same way as UniAD does?
best!
@ZhouYunsong-SJTU

**Comment by zhouyunsong** [comment]
Yeah, basically the same. The producing script is derived from UniAD, and we just rewrote the trajectory in a QA format.

**Comment by hctian713** [comment]
thank you so much！
