### ISSUE TITLE
How to get the QAs about surrounding narration, Action & Decision?

### ISSUE THREAD

**Issue by LuPaoPao** [OpenDriveLab/ELM#5]
I found that the responses to keyword I found that the responses to keyword A were all invalid:
 were all invalid in drivelm_train.json:
like: Apologies, but I do not have information about the surrounding objects at this time.

What do I do if I want to compare these metrics about surrounding narration, Action & Decision?

**Comment by DevLinyan** [comment]
Hi @LuPaoPao, are you suggesting that your model only produces invalid answers? Are you seeking guidance on how to compare your prediction and ground truth? If that's the case, you can directly compare the answers generated by your model with the ground truth answers in `drivelm_train.json` using `language evaluation` as usual.

**Comment by LuPaoPao** [comment]
> Hi @LuPaoPao, are you suggesting that your model only produces invalid answers? Are you seeking guidance on how to compare your prediction and ground truth? If that's the case, you can directly compare the answers generated by your model with the ground truth answers in `drivelm_train.json` using `language evaluation` as usual.

Thank you for your reply and great work. The question is:
1. Most of the ground truth (about keyword surrounding) you provide is invalid in drivelm_train.json,  like Apologies, but I do not have information about the surrounding objects at this time.
2. I would like to get language reviews in different categories. May I ask how the language evaluation of surrounding narration and Action & Decision in your paper was obtained? You give information about box det, box track, box pre and planing, but you don't give the above two categories separately. So I was wondering if I could give these two separate evaluations.

Thank you again for your outstanding contributions.

**Comment by DevLinyan** [comment]
Hi, thanks for pointing it out. You will notice that the drivelm_train.json file contains three keys: GPT, Perception, and Prediction and Planning.

1. We intend to remove the GPT section from the drivelm_train.json file, as the question-answer pairs within this section are not utilized during the training process.
2. The Perception section consists of surrounding narrations, while the Prediction and Planning section pertains to actions and decisions. You have the flexibility to choose either of these sections for evaluation purposes.

**Comment by LuPaoPao** [comment]
> Hi, thanks for pointing it out. You will notice that the drivelm_train.json file contains three keys: GPT, Perception, and Prediction and Planning.
> 
>     1. We intend to remove the GPT section from the drivelm_train.json file, as the question-answer pairs within this section are not utilized during the training process.
> 
>     2. The Perception section consists of surrounding narrations, while the Prediction and Planning section pertains to actions and decisions. You have the flexibility to choose either of these sections for evaluation purposes.

Thank you for your quick reply! Congratulations again for this great job!
