### ISSUE TITLE
How to get Pr@k metric?

### ISSUE THREAD

**Issue by LuPaoPao** [OpenDriveLab/ELM#6]
How to obtain the Pr@k indicators proposed in the paper? I can't seem to find the relevant code.

**Comment by DevLinyan** [comment]
Hi, we have supported the evaluation process for the locaton task. You can find Pr@k [here](https://github.com/OpenDriveLab/ELM/blob/06e26fc5b8b2d7c6f7d37a9774b672e456b7184b/evaluation/location_eval.py#L43).

**Comment by LuPaoPao** [comment]
> How to obtain the Pr@k indicators proposed in the paper? I can't seem to find the relevant code.

So cool! Thank you again for your outstanding contributions. Forgive me for not reviewing the code carefully.
