### ISSUE TITLE
Typo in video_clip_processor.py

### ISSUE THREAD

**Issue by pastapeter** [OpenDriveLab/ELM#8]
one typo in tools/video_clip_processor

```
from lavis.datasets.data_utils load_pickle
```

to

```
from lavis.datasets.data_utils import load_pickle
```

**Comment by DevLinyan** [comment]
Hi @pastapeter, thanks for pointing it out. We will fix it.

**Comment by pastapeter** [comment]
Thanks! 
When will the model be available?

**Comment by DevLinyan** [comment]
Thank you for your attention. We expect to release models gradually before the midpoint of the year.
